theme: jekyll-theme-slate
title: Οπτικοποίηση δεδομένων χορηγιών (UK)
description: Οπτικοποίηση δεδομένων χορηγιών (UK), Εργασία SW 2018, Καπετάνιος Αχιλλέας, Π2015201
links: https://github.com/achkap/D3js-uk-political-donations
       https://achkap.github.io/D3js-uk-political-donations/
